POST http://localhost:8080/candidate/
Content-Type: application/json

{
  "name": "Michael C. Strahl",
  "userName": "michaelstrahl",
  "email": "michaelstrahl.sm@gmail.com",
  "password": "123456",
  "description": "description"
}